### PR TITLE
Move interactive API examples to openfl-contrib

### PR DESCRIPTION
**Pull request by vrancurel**
As we deprecate the interactive API by a more generalized form with the workflow API, we
    decided to keep the examples in this repo.

### CODE REVIEW

**Comment by teoparvanov** [comment]
Thanks, @vrancurel for moving the Interactive API examples out of OpenFL!
@kta-intel, please note this is just a suggested temporary situation for OpenFL 1.7 where the Interactive API is deprecated, but not removed. If we delete it in 1.8, we can also remove all Interactive API examples from here too.

PS: in the meantime, a selection of these examples can be migrated to Workflow API in 1.7

**Comment by kta-intel** [comment]
Thanks @vrancurel and @teoparvanov

Couple questions/comments:
1. have these examples been tested and found to at least be functional?
2. is there a reason why we have decided not to remove them outright from v1.7? Considering that they are archived in previous versions (i.e. [openfl/tree/v1.6](https://github.com/securefederatedai/openfl/tree/v1.6/openfl-tutorials/interactive_api)) it might be safe to just remove them or move them to a subfolder labeled `deprecated` rather than move them here

**Comment by teoparvanov** [comment]
Hi @kta-intel, as you can see in https://github.com/securefederatedai/openfl/pull/1125, the suggestion is to remove those example from the OpenFL repo. Now, the question is whether to archive them or "store" them temporarily in openfl-contrib. In any case, I don't think it's a good investment to spend time fixing them. The only reason to keep them around for a bit is if someone would like to experiment with Director/Envoy while the FederatedRuntime for Workflow API is still in development,

**Comment by teoparvanov** [comment]
@vrancurel the suggestion is to close this PR, as per our offline discussion with @kta-intel on the plan for deprecating Interactive API.

**Comment by vrancurel** [comment]
Decision to keep the examples into the main repo under a "deprecated" folder, so closing this PR without merging.

**Pull request closed without merging**
